// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7pufSxhaAaTLMnlj_Sk3Aty-FNbjvNUk',
    appId: '1:79939892171:web:5b9d4446dd8c6eaa6d7c4e',
    messagingSenderId: '79939892171',
    projectId: 'store21-edf31',
    authDomain: 'store21-edf31.firebaseapp.com',
    storageBucket: 'store21-edf31.firebasestorage.app',
    measurementId: 'G-HB2V98HQVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo_MO2UFeeQaWA3MY4Lb2IpYqKnYlied0',
    appId: '1:79939892171:android:397c1453437998036d7c4e',
    messagingSenderId: '79939892171',
    projectId: 'store21-edf31',
    storageBucket: 'store21-edf31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtDFrdzmvIsgvJt5Qa0FMYcrcTiojXCTM',
    appId: '1:79939892171:ios:4fce5a0fe2dcb8f66d7c4e',
    messagingSenderId: '79939892171',
    projectId: 'store21-edf31',
    storageBucket: 'store21-edf31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtDFrdzmvIsgvJt5Qa0FMYcrcTiojXCTM',
    appId: '1:79939892171:ios:4fce5a0fe2dcb8f66d7c4e',
    messagingSenderId: '79939892171',
    projectId: 'store21-edf31',
    storageBucket: 'store21-edf31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7pufSxhaAaTLMnlj_Sk3Aty-FNbjvNUk',
    appId: '1:79939892171:web:4fb95df6b61dd1c26d7c4e',
    messagingSenderId: '79939892171',
    projectId: 'store21-edf31',
    authDomain: 'store21-edf31.firebaseapp.com',
    storageBucket: 'store21-edf31.firebasestorage.app',
    measurementId: 'G-H7FZ25J2K3',
  );
}
